// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_SE74RkMQ3h0K5cRcTwYkSkmPC1szu8A',
    appId: '1:617155276022:web:69e9e3f8159ecd290a90d7',
    messagingSenderId: '617155276022',
    projectId: 'week6-provider-app',
    authDomain: 'week6-provider-app.firebaseapp.com',
    storageBucket: 'week6-provider-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1scw1CF6Q8belZ5uGSVasvjG9DrboE5Y',
    appId: '1:617155276022:android:890cec0008c23ddd0a90d7',
    messagingSenderId: '617155276022',
    projectId: 'week6-provider-app',
    storageBucket: 'week6-provider-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWhBhGCvXAQVYil8AV1uUAN_DSEG8Y0WA',
    appId: '1:617155276022:ios:9923023f5d9422580a90d7',
    messagingSenderId: '617155276022',
    projectId: 'week6-provider-app',
    storageBucket: 'week6-provider-app.firebasestorage.app',
    iosBundleId: 'com.example.stateManagementWithProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWhBhGCvXAQVYil8AV1uUAN_DSEG8Y0WA',
    appId: '1:617155276022:ios:9923023f5d9422580a90d7',
    messagingSenderId: '617155276022',
    projectId: 'week6-provider-app',
    storageBucket: 'week6-provider-app.firebasestorage.app',
    iosBundleId: 'com.example.stateManagementWithProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_SE74RkMQ3h0K5cRcTwYkSkmPC1szu8A',
    appId: '1:617155276022:web:1ed0fdb744df021f0a90d7',
    messagingSenderId: '617155276022',
    projectId: 'week6-provider-app',
    authDomain: 'week6-provider-app.firebaseapp.com',
    storageBucket: 'week6-provider-app.firebasestorage.app',
  );
}
